/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameRoot from "./scripts/GameRoot"
import AutoMove from "./scripts/AutoMove"
import RepeatBg from "./scripts/RepeatBg"
import BirdCtrl from "./scripts/BirdCtrl"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/GameRoot.js",GameRoot);
		reg("scripts/AutoMove.js",AutoMove);
		reg("scripts/RepeatBg.js",RepeatBg);
		reg("scripts/BirdCtrl.js",BirdCtrl);
    }
}
GameConfig.width = 1920;
GameConfig.height = 1080;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
